version: '3.8'

volumes:
  db:
    driver: local
  cache:
    driver: local
  fserver_data: {}
  vrfs_data: {}

networks:
  vrfs-network:
    driver: bridge

services:

  # db:
  #   image: mongo:7.0.3
  #   restart: unless-stopped
  #   ports:
  #     - '27017:27017'
  #   volumes:
  #     - db:/data/db
  #   networks:
  #     - vrfs-network

  vrfs-cache:
    container_name: vrfs-cache
    image: redis:7.2.3-alpine3.18
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass hSy2TiQFw8Yyzs4oxqjzwvoM
    volumes: 
      - cache:/data
    networks:
      - vrfs-network

  vrfs-fs:
    container_name: vrfs-fs
    build:
      context: .
      dockerfile: ./fileserver/Dockerfile
      target: production
    image: vrfs-fs
    restart: unless-stopped
    depends_on:
      - vrfs-cache
    ports:
      - 9000:9000
    environment:
      GRPC_PORT: ':9000'
      LOG_LEVEL: 'debug'
    links:
      - vrfs-cache
    volumes:
      - ./fs-playground/fs_client_files:/app/fs-playground/fs_client_files:rw
      - fserver_data:/fserver
    networks:
      - vrfs-network

  vrfs-api:
    container_name: vrfs-api
    build:
      context: .
      dockerfile: ./server/Dockerfile
      target: production
    image: vrfs-api
    depends_on:
      - vrfs-cache
      - vrfs-fs
    ports:
      - 50051:50051
    environment:
      GRPC_PORT: ':50051'
      LOG_LEVEL: 'debug'
      REDIS_ENDPOINT: 'vrfs-cache:6379'
      REDIS_PASSWORD: hSy2TiQFw8Yyzs4oxqjzwvoM
      FSAPI_ENDPOINT: 'vrfs-fs:9000'
    links:
      - vrfs-cache
      - vrfs-fs
    volumes:
      - vrfs_data:/vrfs:rw
    networks:
      - vrfs-network
