app:
  name: 'verified-remote-file-storage'
  version: '1.0.0'

grpc:
  port: ':50051'

logger:
  log_level: 'info'

cache:
  endpoint: 'localhost:6379'
  password: 'hSy2TiQFw8Yyzs4oxqjzwvoM'

fsapi:
  endpoint: 'localhost:9000'