// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: libs/protos/vrfs_v1.proto

package vrfs_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VerifiableRemoteFileStorageV1Client is the client API for VerifiableRemoteFileStorageV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VerifiableRemoteFileStorageV1Client interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type verifiableRemoteFileStorageV1Client struct {
	cc grpc.ClientConnInterface
}

func NewVerifiableRemoteFileStorageV1Client(cc grpc.ClientConnInterface) VerifiableRemoteFileStorageV1Client {
	return &verifiableRemoteFileStorageV1Client{cc}
}

func (c *verifiableRemoteFileStorageV1Client) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/vrfs_v1.VerifiableRemoteFileStorageV1/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerifiableRemoteFileStorageV1Server is the server API for VerifiableRemoteFileStorageV1 service.
// All implementations must embed UnimplementedVerifiableRemoteFileStorageV1Server
// for forward compatibility
type VerifiableRemoteFileStorageV1Server interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedVerifiableRemoteFileStorageV1Server()
}

// UnimplementedVerifiableRemoteFileStorageV1Server must be embedded to have forward compatible implementations.
type UnimplementedVerifiableRemoteFileStorageV1Server struct {
}

func (UnimplementedVerifiableRemoteFileStorageV1Server) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedVerifiableRemoteFileStorageV1Server) mustEmbedUnimplementedVerifiableRemoteFileStorageV1Server() {
}

// UnsafeVerifiableRemoteFileStorageV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VerifiableRemoteFileStorageV1Server will
// result in compilation errors.
type UnsafeVerifiableRemoteFileStorageV1Server interface {
	mustEmbedUnimplementedVerifiableRemoteFileStorageV1Server()
}

func RegisterVerifiableRemoteFileStorageV1Server(s grpc.ServiceRegistrar, srv VerifiableRemoteFileStorageV1Server) {
	s.RegisterService(&VerifiableRemoteFileStorageV1_ServiceDesc, srv)
}

func _VerifiableRemoteFileStorageV1_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifiableRemoteFileStorageV1Server).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vrfs_v1.VerifiableRemoteFileStorageV1/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifiableRemoteFileStorageV1Server).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VerifiableRemoteFileStorageV1_ServiceDesc is the grpc.ServiceDesc for VerifiableRemoteFileStorageV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VerifiableRemoteFileStorageV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vrfs_v1.VerifiableRemoteFileStorageV1",
	HandlerType: (*VerifiableRemoteFileStorageV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _VerifiableRemoteFileStorageV1_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "libs/protos/vrfs_v1.proto",
}
